#!/bin/bash

##
#
# Useful for you know.. compiling and running real time ;)
# 

#echo "compiling.."

javac -d bin \
src/main/java/com/soundeavor/indexer/Indexer.java \
src/main/java/com/soundeavor/indexer/config/*.java \
src/main/java/com/soundeavor/indexer/debug/*.java


#echo "running.."
cd bin
#echo ""
#echo ""
#echo ""
java indexer.Indexer "$@"
#echo ""
#echo ""
#echo ""
#echo "returning.."
cd ../